### ISSUE TITLE
Run only on specific files

### ISSUE THREAD

**Issue by fleimgruber** [jackdewinter/pymarkdown#125]
Running v. 0.9.2 via pre-commit using this configuration in .pre-commit-hooks.yaml

```
repos:
  - repo: https://github.com/jackdewinter/pymarkdown
    rev: 0.9.2
    hooks:
      - id: pymarkdown
        name: PyMarkdown
        description: "PyMarkdown - GitHub Flavored Markdown and CommonMark Compliant Linter"
        language: python
        language_version: python3
        entry: pymarkdown
        args: [scan, README.md]
        types: [markdown]
```

### Actual behaviour

All other .md files (also in subdirs of project root) are linted as well.

### Expected  behaviour

Only the README.md is linted.
