### ISSUE TITLE
pre-commit hook fails with alternate extension and README.md

### ISSUE THREAD

**Issue by skwde** [jackdewinter/pymarkdown#1289]
## Prerequisites

* [x] Are you running the latest version of this application?
* [x] Have you checked the [Frequently Asked Questions](https://pymarkdown.readthedocs.io/en/latest/faq) document?
* [x] Have you simplified the bug report to the essential details?
  * [x] Do you have a distinct command line to report?
  * [x] Can you clearly state the configuration for this bug report?
  * [x] Do you have a minimal document that highlights this bug?
  * [x] Are any required files (configuration or Markdown document) attached to the issue?
* [x] Did you perform a cursory search of other issues to look for related issues?

### Bug Type

* [ ] Assertion Failure
* [ ] Documentation
* [ ] Scan/Rule not working as expected
* [ ] Fix/Rule not working as expected
* [x] Other: `pre-commit`

### Description

The `pre-commit` hook fails with

```out
Provided file path 'README.md' is not a valid file. Skipping.
```

 when `--alternate-extension` is used.

### Specifics

- OS: `debian:bookworm`
- `pre-commit hook version` / `pymarkdown`: `v0.9.26`

Use `test.qmd`

```qmd
# another extension md file

abc
```

and `README.md`

```md
# Test

abc
```

with the `pre-commit-config.yml`

```yml
default_stages: ['pre-commit']
repos:
  - repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.26
    hooks:
      - id: pymarkdown
        args: 
          - scan
          - --alternate-extension=.qmd
```

via 

```sh
pre-commit run pymarkdown
```

### Actual Behavior

`pymarkdown` seems to be confused by the `README.md` causing the `pre-commit` hook to fail.

### Expected Behavior

`pymarkdown` should only check files with `.qmd` extension and ignore `README.md`.

**Comment by jackdewinter** [comment]
Sorry that it took long to get back to you.... can you look at https://pymarkdown--1317.org.readthedocs.build/en/1317/advanced_pre-commit/#things-to-watch-out-for and let me know if that solves your issue?  As far as we can tell from here, it solves things on our side.

**Comment by jackdewinter** [comment]
Can you take a look at [this](https://pymarkdown.readthedocs.io/en/latest/advanced_pre-commit/#scanning-markdown-files-with-alternate-extensions-from-pre-commit) and let me know if it helps you?

**Comment by jackdewinter** [comment]
just published a new release.  can you verify if this is fixed?

**Comment by skwde** [comment]
@jackdewinter this is not fixed.

Now no warnings for the `.qmd` files are shown.

I e.g. removed the newline after the heading in both files, while for the `README.md` a warning is triggered, there isn't one shown for the `.qmd` file.

**Comment by jackdewinter** [comment]
can you please share your current "pre-commit-config.yml" file, as well as the files you are testing against, relative directories, etc.  Basically, I would like to try and replicate what you are doing, to find out what is missing.

**Comment by skwde** [comment]
@jackdewinter is the MWE I put in the description above not working for you?

You just have to replace the version of `pymarkdownlint` in the `pre-commit` hook.

**Comment by jackdewinter** [comment]
I just tried this again the other day.  I seriously think that it is solely a pre-commit issue.  Unless you do something like demonstrated in the section https://pymarkdown.readthedocs.io/en/latest/advanced_pre-commit/#scanning-markdown-files-with-alternate-extensions-from-pre-commit , Pre-commit will send all files (or all that have changed) that match PyMarkdown's hook configuration of file type = Markdown to be processed.  So, without any change, pre-commit will only send `.md` files, and not `.qmd` files, to be processed.

**Comment by skwde** [comment]
Sorry for not replying earlier @jackdewinter. 

I just tried again with the latest version using

```yaml
  - repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.32
    hooks:
      - id: pymarkdown
        args: 
          - scan
          - --alternate-extension=.qmd
        files: .*\.qmd$
        types: [file]
```

as suggested here: https://pymarkdown.readthedocs.io/en/latest/advanced_pre-commit/#scanning-markdown-files-with-alternate-extensions-from-pre-commit 

I can confirm that with this I am able to run the hook only on .qmd files.
