### ISSUE TITLE
Automated publication of releases to PyPI

### ISSUE THREAD

**Issue by cpswan** [jackdewinter/pymarkdown#1316]
## Prerequisites

* [ ] Are you running the latest version of this application?
  * 0.9.27 has been released here on GitHub, but hasn't yet found its way to PyPI.
* [x] Have you checked the [Frequently Asked Questions](https://pymarkdown.readthedocs.io/en/latest/faq) document?
* [x] Did you perform a cursory search of other issues to look for related issues?

### Description

Use PyPI [Trusted Publisher](https://docs.pypi.org/trusted-publishers/) via a GitHub Actions workflow.

### Desired Behavior of Feature

Newly tagged releases are published automatically on PyPI by a GitHub Actions workflow that uses the [pypa/gh-action-pypi-publish](https://github.com/pypa/gh-action-pypi-publish) action (along with this repo being configured for Trusted publishing on PyPI). 

Something like:

```yaml
  publish-to-pypi:
    name: Publish package to PyPI
    if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
    needs:
    - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pymarkdownlnt
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@v1
      with:
        skip-existing: true
        attestations: true
```

### What Are the Benefits of This Feature?

PyPI will automatically stay up to date with releases here on GitHub, and there will be no need to manually push packages.

Attestations can be enabled so that people are confident that the packages they're getting from PyPI haven't been meddled with.
