### ISSUE TITLE
[feature] allow user to customize args of pre-commit

### ISSUE THREAD

**Issue by Freed-Wu** [jackdewinter/pymarkdown#28]
```yaml
  - repo: https://github.com/jackdewinter/pymarkdown
    rev: main
    hooks:
      - id: pymarkdown
        args: [-d, md032, -d, md033]
```

It cannot work, because it will be expanded to `pymarkdown scan -d md032 -d md033 test.md` not `pymarkdown -d md032 -d md033 scan test.md`.

Thanks!

**Comment by jackdewinter** [comment]
I am not sure what you are asking for.  Can you be more precise?

**Comment by Freed-Wu** [comment]
Sorry for my representation!

How can user disable some warnings in pre-commit-config?

**Comment by jackdewinter** [comment]
I guess what is confusing me is where the "scan" keyword is coming from in your example.  I would assume from what I see that you would just add an extra "scan" argument at the end of your array.

Also, I would suggest "-d md032,md033" and use a comma separated list.

**Comment by Freed-Wu** [comment]
```yaml
  - repo: https://github.com/jackdewinter/pymarkdown
    rev: 0.8.0
    hooks:
      - id: pymarkdown
        args: [-d, 'md032,md033', scan]
```

will result in

```
pymarkdown....................................................................Failed
- hook id: pymarkdown
- exit code: 2

usage: pymarkdown
       [-h]
       [-e ENABLE_RULES]
       [-d DISABLE_RULES]
       [--add-plugin ADD_PLUGIN]
       [--config CONFIGURATION_FILE]
       [--set SET_CONFIGURATION]
       [--strict-config]
       [--stack-trace]
       [--log-level {CRITICAL,ERROR,WARNING,INFO,DEBUG}]
       [--log-file LOG_FILE]
       {plugins,extensions,scan,version}
       ...
pymarkdown: error: unrecognized arguments: -d
```
