### ISSUE TITLE
Cannot disable rules while using pre-commit hooks

### ISSUE THREAD

**Issue by markeyser** [jackdewinter/pymarkdown#557]
Hi team,

I would like hot to disable rules while using pre-commit. I do not know how. The below setting does not work:

```yaml
  # Markdown lintern
  - repo: https://github.com/jackdewinter/pymarkdown
    rev: 0.9.0
    hooks:
      - id: pymarkdown # code-block-style MD046
        args: ["--disable-rules=md046"]
```

Thanks,

Marcos

**Comment by markeyser** [comment]
I guess I got it. Sorry, I've just carefully read the guide: https://github.com/jackdewinter/pymarkdown/blob/main/docs/pre-commit.md

```yaml
  # Markdown lintern
  - repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.7
    hooks:
      - id: pymarkdown # code-block-style MD046
        args:
          - --disable-rules
          - code-block-style
          - scan
```
