### ISSUE TITLE
Better argument support for pre-commit?

### ISSUE THREAD

**Issue by vunhatchuong** [jackdewinter/pymarkdown#625]
I've been having a hard time trying to config Pymarkdown to fit my needs in `pre-commit`.

For example:
```yaml
-   repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.9
    hooks:
      - id: pymarkdown
        args: [-d, MD041, scan, -r, .]
```

By default pymarkdown doesn't scan /docs folder so I have to use `-r .` but now the output is duplicated:

```bash
./README.md:48:1: MD013: Line length [Expected: 80, Actual: 213] (line-length)
./docs/hello.md:5:1: MD012: Multiple consecutive blank lines [Expected: 1, Actual: 4] (no-multiple-blanks)
README.md:48:1: MD013: Line length [Expected: 80, Actual: 213] (line-length)
```
This behavior doesn't exist if you run the command from terminal.

Now my current problem is I want to ignore line length (MD013) but unable to add this option to `-d`.

```yaml
    hooks:
      - id: pymarkdown
        args: [-d, MD041, MD013, scan, -r, .]
```

I know that I can use a `clean.json` but I don't want to add more files to my project if not necessary.

**Comment by vunhatchuong123** [comment]
Yes `pass_filenames: false` does fix the duplicated output, thanks.

How about multiple rules for `-d` ?

**Comment by vunhatchuong123** [comment]
Yes `pass_filenames: false` does fix the duplicated output, thanks.

How about multiple rules for `-d` ?

**Comment by jackdewinter** [comment]
I had to look to find it... https://github.com/jackdewinter/pymarkdown/blob/main/docs/advanced_configuration.md#plugins
and even then, you have to know that `--disable-rules` and `-d` are the same thing.

As a fresh set of eyes on the documentation, can you suggest a good place or places to place that information so it is more obvious and clear?

**Comment by vunhatchuong123** [comment]
I think it's easy to notice `-d` and `--disable-rules` is the same because it's mentioned in  [Basic Configuration](https://github.com/jackdewinter/pymarkdown#basic-configuration) and when you run `pymarkdown --help`:
 
```bash
...
    version             version of the application

options:
  -h, --help            show this help message and exit
  -e ENABLE_RULES, --enable-rules ENABLE_RULES
                        comma separated list of rules to enable
  -d DISABLE_RULES, --disable-rules DISABLE_RULES
                        comma separated list of rules to disable
....
```
I was able to add another rule by adding another `-d`, so this is the complete config.

```yaml
-   repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.9
    hooks:
      - id: pymarkdown
        pass_filenames: false
        args: [-d, MD041, -d, MD013, scan, -r, .]
```
I feel like this is a `pre-commit` problem, so I think you should add the tutorial in [here](https://github.com/jackdewinter/pymarkdown/blob/main/docs/pre-commit.md#arguments).

**Comment by jackdewinter** [comment]
Can you check https://github.com/jackdewinter/pymarkdown/pull/632 and see if that wording helps?

**Comment by vunhatchuong123** [comment]
Yeah it looks fine, but that PR doesn't mention anything about multiple values for `-d` or `-e` right?

Because `args: [-d, MD041, MD013, scan, -r, .]`  doesn't work. It has to be `args: [-d, MD041, -d, MD013, scan, -r, .]`

**Comment by jackdewinter** [comment]
Will work on that... can you double check something for me?  `args: [-d, "MD041, MD013", scan, -r, .]` works for me.  That is placing quotes around the two md parameters.  Can you verify that on your end?

**Comment by vunhatchuong123** [comment]
I doesn't work for me. The `MD041` still applied but not `MD013`

**Comment by vunhatchuong123** [comment]
@jackdewinter I find out why  `args: [-d, "MD041, MD013", scan, -r, .]` doesn't work. There must be no space between rules, so it has to be `args: [-d, "MD041,MD013", scan, -r, .]` like #632.

For example: 
```yaml
    hooks:
      - id: pymarkdown
        pass_filenames: false
        args: [-d, "MD041,MD013, MD022", scan, ., ./docs]
```
**Only** MD041 and MD013 are disabled here, MD022 isn't because there's a space after the comma.
