### ISSUE TITLE
What is default name for configuration file? Is it possible to set config in pyproject.toml?

### ISSUE THREAD

**Issue by mgzenitech** [jackdewinter/pymarkdown#627]
What is default name for configuration file?

Is it possible to set config in pyproject.toml?
I've tried:
```toml
[tool.pymarkdown]
mode.strict-config = true
log.level = "DEBUG"
```
But it doesn't look like it works
