### ISSUE TITLE
Critical failure in plugin MD031 when parsing a fenced code block in a list item

### ISSUE THREAD

**Issue by arwedus** [jackdewinter/pymarkdown#635]
## Problem report

When analyzing the following markdown file, pymarkdown aborts with the error message `(11,3): Plugin id 'MD031' had a critical failure during the 'next_token' action.`:

````
# Batch Measurement Analysis

## Parameterization

In order to be able to evaluate the measurement noise in a precise way,
following settings are needed during a recompute:

- parameters:

  ```yaml
  - name: EXAMPLE_PARAMS
      parameters:
      - filename: bla.yaml
          spawning_enabled: false
      - filename: blubb.yaml
          spawning_enabled: true
  ```

A recompute with ground truth data is needed
````

## Workaround

The plug-in can handle the fenced code block when it is outside of the scope of the list item.

## Expected result

The above file should be scanned without warnings.

## Configuration and version info

Same as in https://github.com/jackdewinter/pymarkdown/issues/634
