### ISSUE TITLE
YAML format for configuration file

### ISSUE THREAD

**Issue by chriscroome** [jackdewinter/pymarkdown#691]
Has supporting YAML as an alternative configuration file syntax to JSON and TOML been considered?

For example:

```bash
cat .pymarkdown
```
```json
{
  "log": {
    "level": "INFO",
    "stack-trace": true
  }
}
```
```bash
cat .pymarkdown | yq -o=yaml -P
```
```yaml
log:
  level: INFO
  stack-trace: true
```
