### ISSUE TITLE
Line length plugin does not work for bash code block

### ISSUE THREAD

**Issue by fleimgruber** [jackdewinter/pymarkdown#769]
Using pymarkdown via pre-commit config:

```yaml
- repo: https://github.com/jackdewinter/pymarkdown
  rev: v0.9.12
  hooks:
  - id: pymarkdown
    name: PyMarkdown
    description: "PyMarkdown"
    language: python
    language_version: python3
    entry: pymarkdown
    args: [ "-s", "plugins.md013.line_length=$#120", "scan" ]
    types: [markdown]
    files: ^README\.md$
```

and README.md contents:

```markdown
    ```bash
    a command that is longer than 80 characters but shorter than 120 characters... at least now it is...
    ```
```

[MD013](https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md#md013---line-length) is triggered.
