### ISSUE TITLE
`--config` flag doesn't work with `pyproject.toml` file

### ISSUE THREAD

**Issue by hasansezertasan** [jackdewinter/pymarkdown#990]
Hi everyone 👋. Thanks for the great effort 🦾!

I have started to use the pymarkdown today and quite enjoying it! However, I noticed a problem while including it in `pre-commit` hooks.

The `pymarkdown scan . ./docs` command reads the configuration from the `pyproject.toml` file but `pymarkdown --config=pyproject.toml scan . ./docs` doesn't do that and it raises this error:

```console
Specified configuration file 'pyproject.toml' was not parseable as a JSON file or a YAML file.
Specified configuration file 'pyproject.toml' was not parseable as a JSON file or a YAML file.


Specified configuration file 'pyproject.toml' was not parseable as a JSON file or a YAML file.
```

Yep, same sentence three times.

Here is my `pyproject.toml` content:

```toml
[tool.pymarkdown]
plugins.MD013.enabled = false
plugins.MD003.style = "atx"
plugins.MD004.style = "asterisk"
plugins.MD007.indent = 4
plugins.MD033.enabled = false
plugins.MD041.enabled = false
plugins.MD022.enabled = false
```

---

`python = ">=3.8,<4.0"` and `pymarkdownlnt = "^0.9.16"`.
